site_name: Amazon EMR Train-The-Trainer Workshop
repo_name: "vasveena/amazon-emr-ttt-workshop"
repo_url: "https://github.com/vasveena/amazon-emr-ttt-workshop"
docs_dir: "docs"
theme: 
  name: material
  features: 
    - tabs
nav:
  - Introduction: 'index.md'
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - attr_list
    - md_in_html
